INSERT INTO products (name, description, stock, price, category) VALUES
('Women Classic T-Shirt', 'Soft cotton T-shirt designed for everyday comfort.', 120, 19.99, 'WOMEN'),
('Women Slim Fit Jeans', 'High-waisted slim-fit jeans with stretch fabric.', 85, 39.99, 'WOMEN'),
('Women Floral Dress', 'Lightweight floral summer dress with adjustable straps.', 60, 49.99, 'WOMEN'),
('Women Hooded Sweatshirt', 'Warm fleece-lined hoodie perfect for colder days.', 100, 34.99, 'WOMEN'),
('Women Yoga Leggings', 'Moisture-wicking leggings ideal for workouts.', 150, 24.99, 'WOMEN'),
('Women Winter Jacket', 'Insulated jacket designed for extremely cold conditions.', 45, 89.99, 'WOMEN'),
('Women Sports Bra', 'Comfortable medium-support sports bra.', 130, 22.50, 'WOMEN'),
('Women Denim Jacket', 'Classic denim jacket suitable for all outfits.', 70, 54.99, 'WOMEN'),
('Women Cardigan Sweater', 'Soft knitted cardigan perfect for layering.', 95, 29.99, 'WOMEN'),
('Women Running Shoes', 'Lightweight running shoes with breathable mesh.', 80, 69.99, 'WOMEN'),

('Men Classic T-Shirt', 'Regular fit cotton T-shirt for daily wear.', 140, 18.99, 'MEN'),
('Men Straight Fit Jeans', 'Durable straight-fit jeans ideal for casual wear.', 90, 44.99, 'MEN'),
('Men Hoodie Sweatshirt', 'Cozy fleece hoodie with adjustable drawstrings.', 110, 32.99, 'MEN'),
('Men Cargo Shorts', 'Comfortable cargo shorts with multiple pockets.', 100, 27.99, 'MEN'),
('Men Leather Belt', 'Genuine leather belt with metal buckle.', 150, 16.99, 'MEN'),
('Men Running Sneakers', 'Lightweight sneakers designed for athletic use.', 75, 72.50, 'MEN'),
('Men Polo Shirt', 'Classic polo shirt made from breathable fabric.', 130, 24.99, 'MEN'),
('Men Bomber Jacket', 'Trendy bomber jacket with durable outer shell.', 50, 79.99, 'MEN'),
('Men Chino Pants', 'Slim-fit chino pants suitable for work or casual wear.', 90, 34.50, 'MEN'),
('Men Winter Coat', 'Thick insulated coat designed for harsh winters.', 40, 99.99, 'MEN'),

('Kids Graphic T-Shirt', 'Fun graphic T-shirt made from soft cotton.', 160, 14.99, 'KIDS'),
('Kids Denim Shorts', 'Comfortable denim shorts for active kids.', 140, 19.50, 'KIDS'),
('Kids Hoodie', 'Warm hoodie available in multiple colors.', 120, 24.99, 'KIDS'),
('Kids Rain Jacket', 'Waterproof rain jacket perfect for spring weather.', 90, 29.99, 'KIDS'),
('Kids Pajama Set', 'Soft and cozy pajama set with cute prints.', 130, 21.99, 'KIDS'),
('Kids Sneakers', 'Durable sneakers designed for daily play.', 100, 34.99, 'KIDS'),
('Kids School Backpack', 'Lightweight backpack with multiple compartments.', 110, 22.99, 'KIDS'),
('Kids Winter Boots', 'Warm insulated boots suitable for snowy days.', 70, 42.99, 'KIDS'),
('Kids Jogger Pants', 'Comfortable jogger pants for active movement.', 125, 16.99, 'KIDS'),
('Kids Summer Hat', 'Breathable summer hat offering UV protection.', 150, 12.99, 'KIDS'),

('Women Leather Handbag', 'Premium leather handbag with adjustable strap.', 50, 74.99, 'WOMEN'),
('Women Sunglasses', 'Stylish UV-protection sunglasses.', 180, 19.99, 'WOMEN'),
('Women Ankle Boots', 'Fashionable ankle boots with cushioned sole.', 65, 59.99, 'WOMEN'),
('Women Scarf', 'Lightweight patterned scarf.', 200, 14.50, 'WOMEN'),
('Women Bracelet Set', 'Elegant bracelet set for daily wear.', 160, 17.99, 'WOMEN'),

('Men Sports Watch', 'Water-resistant digital sports watch.', 80, 49.99, 'MEN'),
('Men Leather Wallet', 'Slim genuine leather wallet.', 200, 29.99, 'MEN'),
('Men Beanie Hat', 'Warm knit beanie perfect for winter.', 150, 12.99, 'MEN'),
('Men Dress Shoes', 'Classic formal shoes made from premium leather.', 60, 89.99, 'MEN'),
('Men Work Gloves', 'Durable gloves for outdoor and mechanical work.', 140, 15.99, 'MEN'),

('Kids Toy Car', 'Colorful pull-back toy car for toddlers.', 180, 9.99, 'KIDS'),
('Kids Coloring Book', 'Creative coloring book with 50+ pages.', 200, 7.99, 'KIDS'),
('Kids Beach Sandals', 'Light and comfy sandals for summer activities.', 140, 13.99, 'KIDS'),
('Kids Winter Gloves', 'Soft knit gloves for cold weather.', 160, 11.50, 'KIDS'),
('Kids Storybook', 'Illustrated storybook for bedtime reading.', 200, 8.99, 'KIDS'),

('Women Perfume', 'Long-lasting floral fragrance.', 75, 49.99, 'WOMEN'),
('Men Cologne', 'Fresh long-lasting cologne.', 70, 52.99, 'MEN'),
('Kids Bathrobe', 'Soft and absorbent bathrobe for kids.', 90, 24.50, 'KIDS'),
('Women Running Shorts', 'Breathable running shorts with elastic waistband.', 100, 19.99, 'WOMEN'),
('Men Swim Trunks', 'Quick-drying swim trunks ideal for summer.', 110, 22.99, 'MEN');
